use_frameworks!

platform :ios, '8.0'

target 'ZPTextAttribiteFild_Example' do
  pod 'ZPTextAttribiteFild', :path => '../'

  target 'ZPTextAttribiteFild_Tests' do
    inherit! :search_paths

    
  end
end
